theme = "studio-fika"
defaultContentLanguage = "fi"
disableLanguages = ["en"]
disableKinds = ["taxonomy", "term"]
timeout = "120s"

[languages]
    [languages.fi]
        languageCode = "fi"
        title = "Studio FIKA"
        weight = 1

[menu]
    [[menu.main]]
        name = "booking"
        url = "ajanvaraus/"
        weight = 1

    [[menu.main]]
        name = "pricing"
        url = "hinnasto/"
        weight = 2

    [[menu.main]]
        name = "team"
        url = "tiimi/"
        weight = 3

    [[menu.main]]
        name = "contactInfo"
        url = "yhteystiedot/"
        weight = 4

[params]
    [params.theme]
        default = "light"
    [params.mainNavigation]
        logo = "assets/images/logo/logo_black_gold.svg"
    [params.footer]
        logo = "assets/images/logo/logo_white_gold.svg"
    [params.contactInfo]
        tel = "+358 41 3118130"
        email = "info@studiofika.fi"
        streetAddress = "Vesijärvenkatu 34, 15140 Lahti"
        companyId = "3229112-1"
    [params.creditsInfo]
        photographer =  "Iisa"
    [[params.socialMedia]]
        name = "Instagram"
        icon = "instagram"
        profile = "fikalahti"
        url = "https://www.instagram.com/fikalahti/"
    [[params.socialMedia]]
        name = "Facebook"
        icon = "facebook"
        profile = "Studio FIKA"
        url = "https://www.facebook.com/Studio-FIKA-102839872150205/"
    [[params.personnel]]
        image = "images/personnel/johanna.jpg"
        name = "Johanna"
        title = "Blonde Specialist, Balayage"
        introduction = "johannaIntro"
        instagram = "https://www.instagram.com/fika.johanna/"
    [[params.personnel]]
        image = "images/personnel/mira.jpg"
        name = "Mira"
        title = "Parturi-kampaaja"
        introduction = "miraIntro"
        instagram = "https://www.instagram.com/fika.mira/"
    [[params.personnel]]
        image = "images/personnel/miia.jpg"
        name = "Miia"
        title = "Parturi-kampaaja"
        introduction = "miiaIntro"
        instagram = "https://www.instagram.com/fika.miia/"
    [[params.personnel]]
        image = "images/personnel/johanna_k_1.jpg"
        name = "Johanna K"
        title = "Meikkaaja"
        introduction = "johannaKIntro"
        instagram = "https://www.instagram.com/johannakotromakeup/"
        email = "info@studiofika.fi"
    [[params.personnel]]
        image = "images/personnel/lotta.jpg"
        name = "Lotta"
        title = "Kosmetologi, Ripsiteknikko"
        introduction = "lottaIntro"
        instagram = "https://www.instagram.com/fika.lotta/"
    [[params.personnel]]
        image = "images/personnel/iisa.jpg"
        name = "Iisa"
        title = "Parturi-kampaaja"
        introduction = "iisaIntro"
        instagram = "https://www.instagram.com/fika.iisa/"

[imaging]
    quality = 90

[markup]
    [markup.goldmark.renderer]
        unsafe = true
